[book]
authors = ["Joel Courtney"]
language = "en"
src = "src"
title = "Kroki Preprocessor Example"

[preprocessor.kroki-preprocessor]
# Example endpoint configuration
endpoint = "https://kroki.io"

# Run the local version. DONT use this line in your real mdbook.
command = "cargo run --manifest-path ../Cargo.toml"
